generator:

  # `auto` (default) generates `NewError` if possible
  # `on` tells generator to fail if spec does not meet requirements
  # `off` disables `Convenient errors` at all
  convenient_errors: "on"

  # sets generator features:
  # for a full feature list please see
  #   https://github.com/ogen-go/ogen/blob/main/gen/features.go
  features:
    enable:
      - "ogen/otel"
