services:
  minio-s3:
    image: minio/minio:latest
    container_name: minio-s3
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /tmp --console-address ":9001"
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio-s3
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio-s3:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO to be ready...';
        sleep 1;
      done;
      /usr/bin/mc mb myminio/czert;
      exit 0;
      "
volumes:
  minio-db-volume:
