// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"

	ht "github.com/ogen-go/ogen/http"
)

func encodeUploadBOMRequest(
	req UploadBOMReq,
	r *http.Request,
) error {
	const contentType = "application/octet-stream"
	body := req
	ht.SetBody(r, body, contentType)
	return nil
}
