// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetBOMByUrnOperation OperationName = "GetBOMByUrn"
	UploadBOMOperation   OperationName = "UploadBOM"
)
