// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetBOMByUrn implements getBOMByUrn operation.
//
// Retrieve a BOM by URN.
//
// GET /api/v1/bom/{urn}
func (UnimplementedHandler) GetBOMByUrn(ctx context.Context, params GetBOMByUrnParams) (r GetBOMByUrnRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadBOM implements uploadBOM operation.
//
// Upload a CBOM (CycloneDX 1.6).
//
// POST /api/v1/bom
func (UnimplementedHandler) UploadBOM(ctx context.Context, req UploadBOMReq) (r UploadBOMRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
