// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/store.go -destination internal/store/mock/mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Contract is a mock of S3Contract interface.
type MockS3Contract struct {
	ctrl     *gomock.Controller
	recorder *MockS3ContractMockRecorder
	isgomock struct{}
}

// MockS3ContractMockRecorder is the mock recorder for MockS3Contract.
type MockS3ContractMockRecorder struct {
	mock *MockS3Contract
}

// NewMockS3Contract creates a new mock instance.
func NewMockS3Contract(ctrl *gomock.Controller) *MockS3Contract {
	mock := &MockS3Contract{ctrl: ctrl}
	mock.recorder = &MockS3ContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Contract) EXPECT() *MockS3ContractMockRecorder {
	return m.recorder
}

// PutObject mocks base method.
func (m *MockS3Contract) PutObject(arg0 context.Context, arg1 *s3.PutObjectInput, arg2 ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3ContractMockRecorder) PutObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3Contract)(nil).PutObject), varargs...)
}
